### PR TITLE
fix: enable in-memory cache when in multi-tenant mode

### PR DESCRIPTION
**Pull request by amanji**
Resolves: #275

### CODE REVIEW

**Review by TimoGlastra — APPROVED** [review]

**Comment by TimoGlastra** [comment]
I think we need to update shared components / node versions to get CI working again

**Comment by amanji** [comment]
I regenerated the yarn lockfile but now `@credo-ts/cheqd` can't be resolved in the tests.

**Comment by amanji** [comment]
@TimoGlastra is there anything specific I need to get the tests to pass here? I'm a bit stuck on why they may be failing.

**Comment by TimoGlastra** [comment]
There have been some changes to the OpenId4VC module which is causing these issues in tests I think

**Pull request closed without merging**
